stages:
  - build

build:
  stage: build
  tags:
    - windows
  script:
    - echo "Checkout Repository"
    - git clone https://github.com/Twig6943/GH-Offset-Dumper.git
    - echo "Install Visual Studio Build Tools"
    - |
      $vsInstallerUrl = "https://aka.ms/vs/16/release/vs_BuildTools.exe"
      $vsInstallerPath = "$env:TEMP\vs_BuildTools.exe"
      $installDir = "C:\MyVS"

      Invoke-WebRequest $vsInstallerUrl -OutFile $vsInstallerPath

      Start-Process -Wait -FilePath $vsInstallerPath -ArgumentList `
        "--installPath `"$installDir`"", `
        "--add Microsoft.VisualStudio.Workload.VCTools", `
        "--includeRecommended", `
        "--passive", "--norestart", "--wait"
    - echo "Setup MSVC Environment"
    - call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat"
    - echo "Build Solution"
    - |
      call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat" && ^
      cd GH-Offset-Dumper && ^
      msbuild GH-Offset-Dumper.sln /p:Configuration=Release /p:Platform=x64
    - echo "Upload Binaries"
    - |
      $binariesPath = "D:\a\GH-Offset-Dumper\GH-Offset-Dumper\GH-Offset-Dumper\bin\*"
      $artifactsPath = "artifacts/"
      New-Item -ItemType Directory -Force -Path $artifactsPath
      Copy-Item -Path $binariesPath -Destination $artifactsPath -Recurse
  artifacts:
    paths:
      - artifacts/*
