name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        shell: pwsh
        run: |
          $vsInstallerUrl = "https://aka.ms/vs/16/release/vs_BuildTools.exe"
          $vsInstallerPath = "$env:RUNNER_TEMP\vs_BuildTools.exe"
          $installDir = "C:\MyVS"

          Invoke-WebRequest $vsInstallerUrl -OutFile $vsInstallerPath

          Start-Process -Wait -FilePath $vsInstallerPath -ArgumentList `
            "--installPath `"$installDir`"", `
            "--add Microsoft.VisualStudio.Workload.VCTools", `
            "--includeRecommended", `
            "--passive", "--norestart", "--wait"

      - name: Setup MSVC Environment
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat"

      - name: Clone Repo
        run: git clone https://github.com/Twig6943/GH-Offset-Dumper.git

      - name: Build Solution
        shell: cmd
        run: |
          call "C:\MyVS\VC\Auxiliary\Build\vcvars64.bat" && ^
          cd GH-Offset-Dumper && ^
          msbuild GH-Offset-Dumper.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path:  GH-Offset-Dumper/Release
